### ISSUE TITLE
recent for search() and count() error

### ISSUE THREAD

**Issue by developersteve** [danieldevine/bird-elephant#17]
**Describe the bug**
Tried everything on this one (and possibly ive missed something) but keep getting a member function error on recents, tried using oath 1 and 2 (although i know this is an auth 2 call). Poked around the src functions but couldnt find anything, other functions that i can use seem to work ok in that function. 

```
Fatal error: Uncaught Error: Call to a member function recent() on null
```
function array is set as expected

**To Reproduce**
```
$twitter = new BirdElephant($credentials);

$params = array('query' => 'a', 'max_results' => 5);

$tweets->search->recent($params);
```

**Expected behavior**
returns a list of tweets

**Environment (please complete the following information):**
 - Operating System: osx local 
 - PHP 8.1
 - Bird Elephant version: latest

**Additional context**
validated all generated keys with other function contexts (and seems to be working ok elsewhere)

**Comment by danieldevine** [comment]
Hi @developersteve 

I tried to replicate as follows:

```php

$twitter = new BirdElephant($credentials);

$tweets = $twitter->tweets();

$params = [
    'query' => 'a',
    'max_results'  => 5,
];

try {
    $tweets->search()->recent($params);
    var_dump($tweets);
} catch (GuzzleException $e) {
   var_ dump($e->getResponse()->getBody()->getContents());
}

```
This returned the following exception errors:

The `max_results` query parameter value [5] is not between 10 and 100"

There were errors processing your request: Rules must contain at least one positive, non-stopword clause (at position 1)

---

so in other words the issue is with the parameters (when I replicate). 

I use the invalid value 5 in the  example in the documentation, so I'll update that.

Can you try again with a full word as the query and max_results set to 10 and let me know if this works ok for you?

**Comment by developersteve** [comment]
Ahhhh yep that got it! 

Thank you! 

I had the example code from https://birdelephant.com/tweets#search-recent-tweets in there, can i update that page somewhere?

**Comment by danieldevine** [comment]
Great. The docs aren't open sourced at the moment, so I'll make the adjustment shortly.
